source 'https://rubygems.org'

branch = ENV.fetch('SOLIDUS_BRANCH', 'master')
gem 'solidus', github: 'solidusio/solidus', branch: branch

# Provides basic authentication functionality for testing parts of your engine
gem 'solidus_auth_devise'

# This is needed to avoid incompatibilities between this extension and
# old versions of solidus (< 2.5). This can be reverted when Solidus 2.4
# reaches EOL. See https://github.com/solidusio/solidus/pull/2835
if branch < 'v2.5'
  gem 'factory_bot', '4.10.0'
else
  gem 'factory_bot', '> 4.10.0'
end

gemspec
